# Generated by Django 4.2.7 on 2023-12-05 07:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
                ('vendor_code', models.CharField(default=main.models.Vendor.default_vendor_code, editable=False, max_length=10, unique=True)),
                ('on_time_delivery_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quality_rating_avg', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_response_time', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fulfillment_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(default=main.models.PurchaseOrder.default_po_number, editable=False, max_length=20, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('items', models.JSONField(default=main.models.PurchaseOrder.default_items)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('process', 'In Process'), ('completed', 'Completed'), ('return', 'Return'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('quality_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('on_time_delivery_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quality_rating_avg', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('average_response_time', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('fulfillment_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendor')),
            ],
        ),
    ]
